### ISSUE TITLE
Add /submit endpoint 

### ISSUE THREAD

**Issue by husky-parul** [CS6620-S21/Asynchronous-quantum-job-submission-framework#4]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add /submit endpoint to be able to:
-  Submit a Qasm_Obj via `/submit` API
- When the controller receives Qasm_Obj via `/submit` it runs the Qasm_Obj on a simulator
- The simulator returns a `Result` object
- Write a stub/mocker that changes the status/success field in the `Result` object. Let's call this `Mocked_Result`
- The controller adds the Key (job_id) and Mocked_Result in the `incomplete` bucket.
- Returns the `Result.to_dict()` JSON representation to the caller.

**Describe alternatives you've considered**
N/A

**Additional context**
Qiskit API https://qiskit.org/documentation/index.html
JSOn Schemas: https://github.com/Qiskit/ibm-quantum-schemas/tree/main/schemas

**Comment by rsquare2010** [comment]
Handle errors like this and propagate them to the user:

Traceback (most recent call last):
  File "ibm_api.py", line 33, in <module>
    mapped_circuit = transpile(qc, backend=backend)
  File "/Users/rahul/.local/share/virtualenvs/Asynchronous-quantum-job-submission-framew-dJka3f6_/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 240, in transpile
    _check_circuits_coupling_map(circuits, transpile_args, backend)
  File "/Users/rahul/.local/share/virtualenvs/Asynchronous-quantum-job-submission-framew-dJka3f6_/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 277, in _check_circuits_coupling_map
    raise TranspilerError('Number of qubits ({}) '.format(num_qubits) +
qiskit.transpiler.exceptions.TranspilerError: 'Number of qubits (2) in circuit86 is greater than maximum (1) in the coupling_map'

This happens when the QC contains 2 qubits but the backend(ibmq-armonk) supports only one

**Comment by husky-parul** [comment]
While there might be other errors we would want to propagate to the user, this one not. There is a plan to implement a scheduler that will take care of this, submitting jobs with a sufficient amount of qubits stated in the request.
